-- ================================================================================
--   postgres SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   postgres
--   Generated at:      Fri Jan 23 15:30:34 2009
--   Input Files:       exim.dia
-- 
-- ================================================================================



-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 23 15:30:33 2009
--     Input Files:       exim.dia

drop index idx_users_login;
drop index idx_domains_domain;
drop index idx_domains_types_type;
drop index idx_spam_types;
drop index idx_aliases_local_part;
drop index idx_userforward_local_part;
-- alter table users drop constraint users_fk_Id_spam-- (is implicitly done)
-- alter table users drop constraint users_fk_Id_domain-- (is implicitly done)
-- alter table domains drop constraint domains_fk_Id_type-- (is implicitly done)
-- alter table aliases drop constraint aliases_fk_Id_domain-- (is implicitly done)
-- alter table userforward drop constraint userforward_fk_Id_domain-- (is implicitly done)


-- Generated Permissions Drops
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 23 15:30:33 2009
--     Input Files:       exim.dia



-- Special statements for postgres:pre databases
drop sequence aliases_id_seq;
drop sequence userforward_id_seq;
drop sequence domains_id_seq;
drop sequence users_id_seq;

create sequence users_id_seq;
create sequence domains_id_seq;
create sequence userforward_id_seq;
create sequence aliases_id_seq;



-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 23 15:30:33 2009
--     Input Files:       exim.dia

drop view users_view cascade ;
drop view aliases_view cascade ;
drop view userforward_view cascade ;
drop view domains_view cascade ;


-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 23 15:30:33 2009
--     Input Files:       exim.dia

drop table users cascade ;
drop table domains cascade ;
drop table domain_types cascade ;
drop table spam_type cascade ;
drop table aliases cascade ;
drop table userforward cascade ;


-- Generated SQL Schema
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 23 15:30:33 2009
--     Input Files:       exim.dia


-- users
create table users (
  id                        int default NEXTVAL('users_id_seq') not null,
  login                     text,
  name                      text,
  password                  text,
  decrypt                   text,
  uid                       text default 'exim',
  gid                       text default 'mail',
  id_domain                 int,
  quota                     integer,
  status                    integer default 1,
  id_spam                   integer,
  spam_score                integer,
  constraint pk_Users primary key (id)
) ;

-- domains
create table domains (
  id                        int default NEXTVAL('domains_id_seq') not null,
  domain                    text,
  id_type                   int,
  constraint pk_Domains primary key (id)
) ;

-- domain_types
create table domain_types (
  id                        int not null,
  type                      text,
  constraint pk_Domain_types primary key (id)
) ;

-- spam_type
create table spam_type (
  id                        int not null,
  type                      text,
  constraint pk_Spam_type primary key (id)
) ;

-- aliases
create table aliases (
  id                        int default NEXTVAL('aliases_id_seq') not null,
  local_part                text,
  id_domain                 int,
  recipients                text,
  constraint pk_Aliases primary key (id)
) ;

-- userforward
create table userforward (
  id                        int default NEXTVAL('userforward_id_seq') not null,
  local_part                text,
  id_domain                 int,
  recipients                text,
  constraint pk_Userforward primary key (id)
) ;








-- Generated SQL Views
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 23 15:30:33 2009
--     Input Files:       exim.dia


-- users_view
create view users_view as
  select u.login, u.name, u.password, u.decrypt, d.domain, u.quota, u.status, u.id_spam, u.spam_score, u.uid, u.gid
  from users u,
    domains d
  where (u.id_domain = d.id)
;

-- aliases_view
create view aliases_view as
  select a.local_part, d.domain, a.recipients
  from aliases a,
    domains d
  where (a.id_domain = d.id)
;

-- userforward_view
create view userforward_view as
  select f.local_part, d.domain, f.recipients
  from userforward f,
    domains d
  where (f.id_domain = d.id)
;

-- domains_view
create view domains_view as
  select d.domain, t.type
  from domains d,
    domain_types t
  where (d.id_type = t.id)
;



-- Generated Permissions
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 23 15:30:33 2009
--     Input Files:       exim.dia



-- Generated SQL Insert statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 23 15:30:33 2009
--     Input Files:       exim.dia


-- inserts for domain_types
insert into domain_types values ( 0,'LOCAL' ) ;
insert into domain_types values ( 1,'RELAY' ) ;
insert into domain_types values ( 2,'VIRTUAL' ) ;

-- inserts for domains
insert into domains values ( 0,'domain.ru.su',0 ) ;

-- inserts for spam_type
insert into spam_type values ( 0,'NONE' ) ;
insert into spam_type values ( 1,'Body' ) ;
insert into spam_type values ( 2,'Subject' ) ;
insert into spam_type values ( 3,'Reject' ) ;


-- Generated SQL Constraints
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 23 15:30:33 2009
--     Input Files:       exim.dia

create unique index idx_users_login on users  (login,id_domain) ;
create unique index idx_domains_domain on domains  (domain) ;
create unique index idx_domains_types_type on domain_types  (type) ;
create unique index idx_spam_types on spam_type  (type) ;
create unique index idx_aliases_local_part on aliases  (local_part,id_domain) ;
create unique index idx_userforward_local_part on userforward  (local_part,id_domain) ;
alter table users add constraint users_fk_Id_spam
  foreign key (id_spam)
  references spam_type (id)  ;
alter table users add constraint users_fk_Id_domain
  foreign key (id_domain)
  references domains (id)  ;
alter table domains add constraint domains_fk_Id_type
  foreign key (id_type)
  references domain_types (id)  ;
alter table aliases add constraint aliases_fk_Id_domain
  foreign key (id_domain)
  references domains (id)  ;
alter table userforward add constraint userforward_fk_Id_domain
  foreign key (id_domain)
  references domains (id)  ;

